components.json, package-lock.json, package.json, src/index.css
Fix
Fix deletion in  index.css for ShadCN.
Empty
=> [CLUST-17] Fix ShadCN in index.css

.github/workflows/ci.yml, Dockerfile, components.json, package-lock.json, package.json, src/index.css
Feature
CI
- Set up GitHub Actions CI workflow for the frontend.
- Automatically run ESLint, Prettier, and Vite production build 
1. docker pull -t clustron-frontend .
2. docker run -d -p 8080:80 clustron-frontend
3. open http://localhost:8080
=> [CLUST-17] Initialize frontend CI

.github/workflows/close.yaml
- Fix
- Add event number in close workflow
=> Fix close workflow

.github/workflows/main.yaml, .github/workflows/pull-request.yaml
- CI
- Change platform of image to arm64 due to new machine
=> [CLUST-48] Change platform of image

src/App.tsx, src/components/Navbar.tsx, src/components/OnboardingForm.tsx, src/components/auth/AuthProvider.tsx, src/components/auth/ProtectedRoute.tsx, src/lib/auth/authContext.ts, src/locales/en.json, src/locales/zh.json, src/pages/Callback.tsx
- Feature
- Prevent user from accessing protected pages and redirect them back to onboarding page when their role is `role_not_setup`.
- Hide NavLinks in the navbar when the user is on the onboarding page.
=> Handle role_not_setup for protecting route

src/hooks/useGlobalRole.ts, src/hooks/useRoleMapper.ts
- Fix
- Resolve linting errors to let it deploy
=> Fix lining errors

src/pages/GroupOverview.tsx
=> fix: layout problem

.env.production, .env.staging, Dockerfile, nginx.conf
- Fix
- Fix nginx config and env variable
=> fix: fix nginx config and env variable

src/App.tsx
- Feature
- Add health check endpoint `/health` to let the deploy service know whether the frontend service is up or not.
=> Add health check endpoint

src/components/group/GroupMemberTable.tsx, src/lib/permission.ts, src/pages/GroupOverview.tsx, src/pages/GroupPage.tsx, src/pages/GroupSettings.tsx
- Fix
- Resolve button showing problem in overview
- TA cannot see the addMember problem
=> [CLUST-79]  & [CLUST-77] modify addbutton in overview page & solve TA cannot see butoon problem

src/components/group/GroupMemberTable.tsx, src/lib/permission.ts, src/pages/GroupPage.tsx
- Fix
-  student should not see the course grape detail after enter one course
=> [CLUST-73]  fix student's view after enter one course

src/components/group/AddMemberButton.tsx, src/components/group/AddMemberRow.tsx, src/components/group/GroupMemberRow.tsx, src/components/group/GroupMemberTable.tsx, src/components/group/GroupSideBar.tsx, src/components/group/MemberDeleteButton.tsx, src/locales/en.json, src/locales/zh.json, src/pages/AddMemberPage.tsx, src/pages/CreateGroup.tsx, src/pages/GroupList.tsx, src/pages/GroupOverview.tsx, src/pages/GroupSettings.tsx
- Feature
- Complete i18n implementation for the missing group-related sections
=> [CLUST-46] Complete i18n

src/components/group/GroupMemberRow.tsx, src/components/group/GroupMemberTable.tsx, src/pages/AddMemberPage.tsx, src/pages/Home.tsx
- Fix
- use Button in shadcn instead of build-in button
=> [CLUST-80] switch from button to Button

src/components/group/AddMemberRow.tsx, src/components/group/GroupMemberRow.tsx, src/components/group/GroupMemberTable.tsx, src/components/group/MemberDeleteButton.tsx, src/index.css, src/pages/AddMemberPage.tsx, src/pages/CreateGroup.tsx, src/pages/GroupList.tsx, src/pages/GroupOverview.tsx, src/pages/GroupPage.tsx, src/pages/GroupSettings.tsx
- Fix
- brighten text color in dark mode
=> [CLUST-82] modify text color in dark mode

src/components/group/AddMemberRow.tsx, src/components/group/GroupMemberRow.tsx, src/components/group/GroupMemberTable.tsx, src/components/group/MemberDeleteButton.tsx, src/pages/AddMemberPage.tsx, src/pages/CreateGroup.tsx, src/pages/GroupList.tsx, src/pages/GroupOverview.tsx, src/pages/GroupPage.tsx, src/pages/GroupSettings.tsx
- Fix
- Add peading icon in some buttons in group
=> [CLUST-77] add pending UI in group 

src/components/OnboardingForm.tsx, src/components/auth/AuthProvider.tsx, src/components/setting/SettingAddKeyForm.tsx, src/lib/auth/authContext.ts, src/lib/request/api.ts, src/lib/request/deletePublicKey.ts, src/lib/request/getPublicKey.ts, src/lib/request/getSettings.ts, src/lib/request/refreshAuthToken.ts, src/lib/request/saveOnboardingInfo.ts, src/lib/request/savePublicKey.ts, src/lib/request/saveSettings.ts, src/locales/en.json, src/locales/zh.json, src/pages/Callback.tsx, src/types/type.ts
- Refactor
- Wrap settings and authentication requests using the unified api function
- Define `AuthCookie` and `Settings` types for API response typing
- Let Linux username format validation be handled by the response from backend
=> [CLUST-81] Wrapper all requests into unified api function

.env, src/components/group/PendingMemberRow.tsx, src/components/group/PendingMemberTable.tsx, src/components/ui/pagination.tsx, src/hooks/useGetPendingMembers.ts, src/hooks/useRemovePendingMember.ts, src/hooks/useRoleMapper.ts, src/hooks/useUpdatePendingMember.ts, src/lib/request/groupPendingMembers.ts, src/locales/en.json, src/locales/zh.json, src/pages/AddMemberPage.tsx, src/pages/GroupPage.tsx, src/pages/GroupSettings.tsx, src/pages/layouts/GroupLayout.tsx, src/types/group.ts
- Feat
- Add pending table
- Resolve main branch merge problem
=> [CLUST-95] add pending tableUI-v2

.gitignore, package.json, src/components/group/GroupMemberTable.tsx, src/hooks/useGetMembers.ts, src/hooks/useUpdateMember.ts, src/lib/request/getGroups.ts, src/lib/request/getMembers.ts, src/lib/request/updateMember.ts, src/types/group.ts
- Feature
- Add pagination in group member table
=> [CLUST-118] add pagination  in group member table

src/components/OnboardingForm.tsx, src/locales/en.json, src/locales/zh.json
- Fix
- Add more conditional statements to distinguish the error type for onboarding form
=> [CLUST-152] Handle invalid username when onboard

src/components/setting/SettingLinuxUsernameForm.tsx
- Refactor
- Since this feature is difficult for the back-end to implement, we remove the button for now
=> [CLUST-140] Remove the save-btn in linux username setting

src/pages/GroupSettings.tsx
- Fix
- Resolve transfer button disable bug in group page
=> [CLUST-157]  disable transfer button when archived

.deploy/snapshot/compose.yaml, .deploy/snapshot/deploy.sh, .github/workflows/close.yaml, .github/workflows/pull-request.yaml
- CD/Chore
- Alter the image and container name in the snapshot deploy Docker Compose to enable the deployment of the PR snapshot
=> [CLUST-165] Deploy PR snapshot
